GET {{host}}

### ------------------------------------ tags
GET {{host}}/posts/tags

### create - tag
POST {{host}}/posts/tags
Content-Type: application/json

{"tname": "ttt11"}

### ------------------------------------ posts
### post - one
GET {{host}}/posts/32

### post - all
GET {{host}}/posts

### post - by tagname
GET {{host}}/posts?tname=tag111

### update user - small (except passwd, profile)
PATCH {{host}}/posts/1
Content-Type: application/json

{
  "id": 1,
  "title": "홍길동 title22...",
  "content": "content2222...",
"writer": 14,
  "tags": [{ "tname": "tag111" }, { "tname": "tag112" }]
}

### ------------------------------------ users
### user list
GET {{host}}/users?page=2

### user - one
GET {{host}}/users/14

### create - user with profile & addrs
POST {{host}}/users
Content-Type: application/json

{
  "name": "홍길동14",
  "email": "indiflex14@gmail.com",
  "passwd": "as121a!@#sdf",
  "profile": {
    "photo": "/upload/hong1.png"
  },
  "addrs": [
    {"street": "선유로 9길 30", "detail": "102동 11호"}
  ]
}

### create - full
POST {{host}}/users
Content-Type: application/json

{
  "name": "홍길동10",
  "email": "indiflex10@gmail.com",
  "passwd": "as121a!@#sdf",
  "profile": {
    "photo": "/upload/hong32.png"
  },
  "addrs": [
    {"street": "선유로 9길 30", "detail": "102동"},
    {"street": "선유로 9길 31", "detail": "103동"}
  ],
  "auths": [
    {"id": 1, "authname": "."},
    {"id": 2, "authname": "."}
  ]
}

### update user - small (except passwd, profile)
PATCH {{host}}/users/10
Content-Type: application/json

{
  "name": "홍길동9",
  "email": "indiflex9@gmail.com",
  "profile": {
    "photo": "/upload/hong6.png",
    "role": 0
  },
  "addrs": [
    {"street": "선유로 9길 30", "detail": "112동"},
    {"street": "선유로 9길 31", "detail": "113동"}
  ],
  "auths": [
    {"id": 1, "authname": "."},
    {"id": 3, "authname": "."}
  ]
}

###
GET {{host}}/users/1

### user - find-one
GET {{host}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6Iu2Zjeq4uOuPmTEiLCJlbWFpbCI6ImluZGlmbGV4MUBnbWFpbC5jb20iLCJpYXQiOjE2OTU0NTc4MjksImV4cCI6MTY5NTQ3MjgyOSwiYXVkIjoiYXBwLmNvbSIsImlzcyI6ImFwcC5jb20ifQ.yyQXgggpXin_sC20gAejJOYmDHJgkYC-Skcn7fbrF1E

### user - delete
DELETE {{host}}/users/8


### auths - all
GET {{host}}/users/auths

### auths - create
POST {{host}}/users/auths
Content-Type: application/json

{
  "authname": "Readable"
}

### default-value-pipe
GET {{host}}/users/123x/defpipe

### verify
GET {{host}}/users/verify?email=indiflex2@gmail.com&token=ttttt

### ------------------------------------ services

### redirect
GET {{host}}/redirect-hello?nickname=홍123&addr=서울&age=23

### serviceB test
GET {{host}}/serviceB

###
GET {{host}}/sayHello

###

POST {{host}}
Content-Type: application/json

{
  name: 'xxx'
}
